### ISSUE TITLE
No Version for 8.8.12 Available

### ISSUE THREAD

**Issue by nnabros** [webflo/drupal-core-require-dev#19]
Will there be a release for this anytime soon? This requirement for webflo is not allowing me upgrade a Drupal Core 8.8.11 website.

**Comment by malaynayak** [comment]
Any update on this as this is blocking drupal core update to 8.8.12

**Comment by webflo** [comment]
Fixed it today. https://github.com/webflo/drupal-core-require-dev/releases/tag/8.8.12

**Comment by webflo** [comment]
Please note this package is deprecated. You should switch to core-dev Package https://packagist.org/packages/drupal/core-dev . These functionality is identical. Thanks!
