### ISSUE TITLE
Why not use require-dev instead of require and consolidate with webflo/drupal-core-strict?

### ISSUE THREAD

**Issue by osopolar** [webflo/drupal-core-require-dev#4]
I was wondering why the required dev packages where placed under `require` and not `require-dev`.

There is also a virtual package https://github.com/webflo/drupal-core-strict. Would it be possible to merge both having "strict" stuff under `require` and the dev stuff under `require-dev`?

**Comment by gapple** [comment]
Composer won't install `require-dev` packages of sub-dependencies, only `require`d packages are recursively included in the dependency graph; this applies to packages that are added to both `require` and `require-dev` of the root composer.json.

**Comment by webflo** [comment]
@gapple Thanks for your help.

@osopolar  ``require-dev`` is a root-only property. See https://getcomposer.org/doc/04-schema.md#require-dev and https://getcomposer.org/doc/04-schema.md#root-package for further information on this topic.
