### ISSUE TITLE
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.

### ISSUE THREAD

**Issue by Chris-Archer-Upbeat** [webflo/drupal-core-require-dev#7]
When running composer update or composer install I now get: `Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.`

**Comment by IT-Cru** [comment]
Same problem here. I think phpunit-mock-objects is now build in into phpunit/phpunit 7.x/8.x itself. So perhaps here only an upgrade of phpunit/phpunit will solve our problem with abandoned phpunit/phpunit-mock-objects package.

See also: https://github.com/sebastianbergmann/phpunit-mock-objects/issues/425

**Comment by Berdir** [comment]
This has nothing to do with this project, it just reflects what drupal/core requires.

**Comment by webflo** [comment]
@Berdir is correct. This project is build from drupal/core. We should get rid of this package in Drupal core.
