### ISSUE TITLE
Allow 8.7.0 stable to be updated to

### ISSUE THREAD

**Issue by seanhamlin** [webflo/drupal-core-require-dev#8]
I am looking to upgrade to the latest stable release

```
$ composer prohibits drupal/core:8.7.0
webflo/drupal-core-require-dev  8.7.0-rc1  requires  drupal/core (8.7.0-rc1)
```

I believe there needs to be a new release of `webflo/drupal-core-require-dev` for this to happen.

**Comment by webflo** [comment]
Thanks for the bug-report. I'm debugging the problem.

**Comment by webflo** [comment]
Fixed.

**Comment by seanhamlin** [comment]
Thanks!
